# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
  - job: Build

    pool:
      vmImage: 'windows-latest'

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
      displayName: 'Install API dependencies'
      workingDirectory: 'api'
  
    - script: |
        npm run build
      displayName: 'Build API'
      workingDirectory: 'api'

    - task: CopyFiles@2
      displayName: 'Copy API files'
      inputs:
        SourceFolder: 'api'
        Contents: |
          dist\**
          host.json
          initialise\**
          login\**
          node_modules\**
          package.json
          ping\**
          proxies.json
        TargetFolder: 'api\deploy'
        CleanTargetFolder: true
        OverWrite: true

    - task: ArchiveFiles@2
      displayName: 'Archive API files'
      inputs:
        rootFolderOrFile: 'api\deploy'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)\api.zip'
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      displayName: "Publish API artifact"
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'whatsin-api'
        publishLocation: 'Container'
        
    - script: |
        npm install
      displayName: 'Install UI dependencies'
  
    - script: |
        npm run build
      displayName: 'Build UI'

    - task: PublishBuildArtifacts@1
      displayName: "Publish UI artifact"
      inputs:
        PathtoPublish: 'dist'
        ArtifactName: 'whatsin'
        publishLocation: 'Container'